# Generated by Django 4.2.7 on 2023-11-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.CharField(max_length=100)),
            ],
        ),
    ]
