# Generated by Django 4.2.7 on 2023-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0003_remove_reserva_id_reserva_correo_alter_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
